#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
